### ISSUE TITLE
Proposal: Middleware redesign

### ISSUE THREAD

**Issue by louy** [urbanmassage/node-rabbitr#34]
Middleware in their current shape are confusing and limited. I suggest the following api redesign:

```ts
// RPC
rabbit.middleware(async (message, next) => {
  // Pre-exec logic
  try {
    const response = await next();
    // Post-exec logic
    return response;
  } catch (error) {
    // Post-exec error logic
    throw error;
  }
});

// PubSub
rabbit.middleware(async (message, next) => {
  // Pre-exec logic
  try {
    await next();
    // Post-exec logic (ack)
  } catch (error) {
    // Post-exec error logic (nack)
    throw error;
  }
});
```

The idea is passing a `next` function to middleware, which when executed would execute the message handler and return a promise with its response (or acknowledgement status in pubsub). This way, we can have pre- and post-exec hooks in the same middleware function.

The way to tell the difference between RPC and PubSub would be a new attribute like `IMessage.isRPC` which is a boolean.

More things to experiment with:
- `priority` option for `#middleware`.

**Comment by louy** [comment]
## Implementation Details
This will be a breaking change anyway so we can get rid of the old middleware functionality.

To start, we should have two functions: `Rabbitr#middleware` which is public and `Rabbitr#runMiddleware` which is private.

`Rabbitr#middleware` should have the signature:

```ts
middleware<Request>(fn: (message: IMessage<T>, next: () => Bluebird<void>) => PromiseLike<void>): void;
middleware<Request, Response>(fn: (message: IMessage<T>, next: () => Bluebird<Response | void>) => PromiseLike<Response | void>): void;
```
and whenever it gets called it should store `fn` in a private array.

Next, `IMessage` should have an `isRPC` attribute. Should be straight forward.

Lastly, `useMiddleware` should have the following signature:
```ts
private useMiddleware(message: IMessage<any>): Bluebird<any>;
```

It should loop through all functions in private middleware array and run them in sequence similar to a [compose function](http://blakeembrey.com/articles/2014/01/compose-functions-javascript/).

**Comment by gileze33** [comment]
LGTM

**Comment by louy** [comment]
Done in #54
